package york.studentevents.repository.sql;

import java.util.List;
import java.util.NoSuchElementException;
import java.util.Optional;
import java.util.UUID;
import york.studentevents.subscriptions.ISubscription;
import york.studentevents.subscriptions.ISubscriptionRepository;
import york.studentevents.subscriptions.Subscription;

/**
 * Database-backed implementation of {@link ISubscriptionRepository}, adapting Spring Data JPA to
 * the domain repository contract.
 *
 * <p>Persistence is delegated to a {@link JpaSubscriptionRepository}, whose implementation is
 *     generated by Spring Data at runtime. This adapter translates between the two layers: the
 *     concrete {@link Subscription} entity is widened to the {@link ISubscription} interface on the
 *     way out, a missing row is mapped to {@link Optional#empty()}, and a delete against a missing
 *     row is reported as the {@link java.util.NoSuchElementException} that the
 *     {@link york.studentevents.repository.IRepository} contract requires, rather than the
 *     framework exception that Spring Data would otherwise raise.
 *
 * <p>This is the intended production implementation of {@link ISubscriptionRepository}, superseding
 *     the hash-map backed
 *     {@link york.studentevents.repository.inmemory.InMemorySubscriptionRepository}.
 *
 * @see ISubscriptionRepository
 * @see JpaSubscriptionRepository
 * @see ISubscription
 */
public class SubscriptionRepositoryAdapter implements ISubscriptionRepository {

  private final JpaSubscriptionRepository jpa;

  /**
   * Constructs an adapter that delegates persistence to the given Spring Data repository.
   *
   * @param jpa the Spring Data repository to delegate to; must not be {@code null}
   */
  public SubscriptionRepositoryAdapter(JpaSubscriptionRepository jpa) {
    this.jpa = jpa;
  }

  @Override
  public void save(ISubscription entity) {
    Subscription concreteEntity = (Subscription) entity;
    if (concreteEntity == null) {
      throw new IllegalArgumentException("entity cannot be null");
    }
    jpa.saveAndFlush(concreteEntity);
  }

  @Override
  public void delete(UUID id) {
    if (id == null) {
      throw new IllegalArgumentException("id cannot be null");
    }
    if (!jpa.existsById(id)) {
      throw new NoSuchElementException("No entity with the given ID exists within the database.");
    }
    jpa.deleteById(id);
  }

  @Override
  public Optional<ISubscription> findByID(UUID id) {
    if (id == null) {
      throw new IllegalArgumentException("id cannot be null");
    }
    Optional<Subscription> concreteEntity = jpa.findById(id);

    // Cast the concrete entity to its interface
    Optional<ISubscription> interfaceEntity;
    try {
      interfaceEntity = Optional.of((ISubscription) concreteEntity.get());
    } catch (NoSuchElementException e) {
      interfaceEntity = Optional.empty();
    }
    return interfaceEntity;
  }

  @Override
  public Optional<ISubscription> findByID(UUID userId, UUID eventId) {
    if (userId == null || eventId == null) {
      throw new IllegalArgumentException("userId and eventId fields cannot be null");
    }

    List<Subscription> subList = jpa.findByUserIdAndEventId(userId, eventId);
    
    // Retrieve the element, cast it to its interface, and wrap in an optional
    Optional<ISubscription> interfaceEntity;

    if (subList.size() == 1) {
      Subscription element = subList.getFirst();
      interfaceEntity = Optional.of(element);
    } else if (subList.size() == 0) {
      interfaceEntity = Optional.empty();
    } else {
      throw new IllegalStateException("Multiple subscriptions exist between the given user and"
          + " event");
    }

    return interfaceEntity;
  }

  @Override
  public List<ISubscription> findAll() {
    return jpa.findAll()
        .stream()
        .map(sub -> (ISubscription) sub)
        .toList();
  }

  @Override 
  public List<ISubscription> findAllByEventId(UUID eventId) {
    return jpa.findByEventId(eventId)
        .stream()
        .map(sub -> (ISubscription) sub)
        .toList();
  }

  @Override 
  public List<ISubscription> findAllByUserId(UUID userId) {
    return jpa.findByUserId(userId)
        .stream()
        .map(sub -> (ISubscription) sub)
        .toList();
  }
}
